//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApp.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SubmitSingle", ReplyAction="http://tempuri.org/IService1/SubmitSingleResponse")]
        void SubmitSingle(DAL.DTOs.SubmitOrderDTO submitOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SubmitSingle", ReplyAction="http://tempuri.org/IService1/SubmitSingleResponse")]
        System.Threading.Tasks.Task SubmitSingleAsync(DAL.DTOs.SubmitOrderDTO submitOrder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SubmitMultiple", ReplyAction="http://tempuri.org/IService1/SubmitMultipleResponse")]
        void SubmitMultiple(DAL.DTOs.SubmitOrderDTO[] submitOrderList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SubmitMultiple", ReplyAction="http://tempuri.org/IService1/SubmitMultipleResponse")]
        System.Threading.Tasks.Task SubmitMultipleAsync(DAL.DTOs.SubmitOrderDTO[] submitOrderList);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ClientApp.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ClientApp.ServiceReference1.IService1>, ClientApp.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SubmitSingle(DAL.DTOs.SubmitOrderDTO submitOrder) {
            base.Channel.SubmitSingle(submitOrder);
        }
        
        public System.Threading.Tasks.Task SubmitSingleAsync(DAL.DTOs.SubmitOrderDTO submitOrder) {
            return base.Channel.SubmitSingleAsync(submitOrder);
        }
        
        public void SubmitMultiple(DAL.DTOs.SubmitOrderDTO[] submitOrderList) {
            base.Channel.SubmitMultiple(submitOrderList);
        }
        
        public System.Threading.Tasks.Task SubmitMultipleAsync(DAL.DTOs.SubmitOrderDTO[] submitOrderList) {
            return base.Channel.SubmitMultipleAsync(submitOrderList);
        }
    }
}
